### ISSUE TITLE
How do you set the initial route?

### ISSUE THREAD

**Issue by chadhobson** [pritishvaidya/create-react-native-redux-app#1]
Playing around with Saga pattern and stumbled onto your app here. How are you setting the initial route? I can add a second route in AppNavigation.js and change the initial state in NavigationRedux.js to point to this new route but it keeps loading LaunchScreen. I'm also accustomed to an older React Navigation release so maybe something changed there and that's my problem?

**Comment by pritishvaidya** [comment]
Since I've used Redux Integration in this kit, therefore you can find the relevant code in `App/Redux/NavigationRedux`, I've exposed two variables from the `redux store` `{ persistor, store }`, therefore you may use anything you want, with or without persistance. If you want the `NavigationRedux` to not persist the data into the storage then you can blacklist it in the `persistConfig`

**Comment by chadhobson** [comment]
Look at that, figured it out as soon as I submitted the issue. Purge the persistor! Back to learning...
